### ISSUE TITLE
Front end demo: setModalState replacing, not merging

### ISSUE THREAD

**Issue by kleydon** [flik930/graphql-express-mongo-jwt-docker-boilerplate#1]
In the front-end demo, setModalState is replacing the object, rather than merging in particular values.

According to:
https://reactjs.org/docs/hooks-reference.html#usestate

"Unlike the setState method found in class components, useState does not automatically merge update objects. You can replicate this behavior by combining the function updater form with object spread syntax:
setState(prevState => {
  return {...prevState, ...updatedValues};
});"

Thanks for creating this project. Great resource!

**Comment by flik930** [comment]
Thanks for reminding @kleydon, will have an update soon.😊

**Comment by flik930** [comment]
Just updated.
